export = {
  REQUIRE_USER_MEDIA: 'VIDEO_REQUIRE_USER_MEDIA',
  SET_VIDEO_ELEMENT: 'VIDEO_SET_VIDEO_ELEMENT',
  SET_MEDIA_STREAM: 'VIDEO_SET_MEDIA_STREAM',
  SET_IS_DISABLED_USER_MEDIA: 'VIDEO_SET_IS_DISABLED_USER_MEDIA',
  ON_CAN_PLAY: 'VIDEO_ON_CAN_PLAY',
  ON_PLAY: 'VIDEO_ON_PLAY',
  ON_PAUSE: 'VIDEO_ON_PAUSE'
} as const
