export = {
  TOGGLE_MENU: 'TOGGLE_MENU',
  CLOSE_MENU: 'CLOSE_MENU',
  TOGGLE_VISIBLE_DETECTED_RECT: 'TOGGLE_VISIBLE_DETECTED_RECT',
  ON_RESIZE_WINDOW: 'ON_RESIZE_WINDOW',
  RESET_DETECTED_BOUNDING_BOX: 'RESET_DETECTED_BOUNDING_BOX'
} as const
